repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile=black', '--balanced']

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        types_or: [python, pyi]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8==5.0.4"
          - "flake8-quotes==3.3.1"
          - "flake8-pyproject==1.2.3"
