repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: isort
        name: "Sort imports"
        language: system
        types: [file, python]
        files: .
        entry: isort
        args: ['--profile', 'black', '--line-length', '120', '--balanced']

  - repo: local
    hooks:
      - id: black
        name: "Check code formatting"
        language: system
        entry: black
        types_or: [python, pyi]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8==5.0.4"
          - "flake8-quotes==3.3.1"
          - "flake8-pyproject==1.2.3"
