[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
pythonpath = ['src']
log_format = '%(asctime)s %(levelname)s %(message)s'
log_date_format = "%y-%m-%d %H:%M:%S"
log_cli = true

[tool.coverage.run]
branch = true
source = ['src']

[tool.coverage.report]
show_missing = true

[tool.flake8]
max-line-length = 120
extend-exclude = 'venv/*'
max-complexity = 18
inline-quotes = "\""
